# Generated by Django 4.2.26 on 2025-11-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkrd', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
