# Generated by Django 4.2.26 on 2025-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkrd', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
