# Generated by Django 4.2.26 on 2025-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkrd', '0006_notification_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
