# Generated by Django 5.2.5 on 2025-11-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkrd', '0008_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lkrd.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_sendings', to='lkrd.card'),
        ),
    ]
