# Generated by Django 5.2.5 on 2025-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkrd', '0010_alter_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
